"""
Report writer — formats the final investigation context into a structured
markdown RCA report and writes it to the reports/ directory.
"""

from datetime import datetime, timezone
from pathlib import Path


# __file__ = src/incident_pilot/utils/report.py
# .parent.parent.parent = src/  → .parent * 4 = project root
REPORT_DIR = Path(__file__).parent.parent.parent.parent / "reports"


def write_report(context: dict, output_dir: str | None = None) -> str:
    """
    Write a structured RCA markdown report from the investigation context.

    Parameters
    ----------
    context : dict
        The accumulated context dict returned by pipeline.run_pipeline().
    output_dir : str | None
        Directory to write the report into. Defaults to the project-level reports/ folder.

    Returns
    -------
    str
        Absolute path of the written report file.
    """
    out_dir = Path(output_dir) if output_dir else REPORT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    filename = f"RCA_{timestamp}.md"
    filepath = out_dir / filename

    report = _build_report(context)
    filepath.write_text(report, encoding="utf-8")
    return str(filepath)


def _build_report(context: dict) -> str:
    """Assemble the full markdown report string from context."""
    triage    = context.get("triage", {})
    keywords  = context.get("sql_keywords", [])
    sql_rows  = context.get("sql_raw_results", [])
    rca       = context.get("rca_report", "No RCA produced.")
    escalation = context.get("escalation", "Unknown")
    ticket    = context.get("ticket", "")
    log_file  = context.get("log_file_used", "none")
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        f"# Incident Investigation Report",
        f"",
        f"**Generated:** {timestamp}  ",
        f"**Tool:** incident-pilot v0.1.0  ",
        f"**Escalation:** {escalation}",
        f"",
        f"---",
        f"",
        f"## Original Ticket",
        f"",
        f"> {ticket}",
        f"",
        f"---",
        f"",
        f"## Triage",
        f"",
        f"| Field     | Value |",
        f"|-----------|-------|",
        f"| Severity  | {triage.get('severity', '?')} |",
        f"| Component | `{triage.get('component', '?')}` |",
        f"| Category  | {triage.get('category', '?')} |",
        f"| Summary   | {triage.get('summary', '?')} |",
        f"",
        f"---",
        f"",
        f"## SQL Investigation",
        f"",
        f"**Keywords searched:** `{', '.join(keywords)}`  ",
        f"**Incidents matched:** {len(sql_rows)}",
        f"",
    ]

    if sql_rows:
        lines += [
            f"| ID | Title | Component | Severity | Status |",
            f"|----|-------|-----------|----------|--------|",
        ]
        for row in sql_rows:
            lines.append(
                f"| {row['id']} | {row['title']} | `{row['component']}` | "
                f"{row['severity']} | {row['status']} |"
            )
        lines.append("")

    lines += [
        f"---",
        f"",
        f"## Log Analysis",
        f"",
        f"**Log file analysed:** `{log_file}`",
        f"",
        context.get("log_analysis", "No log analysis available."),
        f"",
        f"---",
        f"",
        f"## Root Cause Analysis",
        f"",
        rca,
        f"",
        f"---",
        f"",
        f"*Report generated by [incident-pilot](https://github.com/amosalloyce/incident-pilot) "
        f"— a multi-agent TSE investigation assistant.*",
    ]

    return "\n".join(lines)
